<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "md_saml"
 *
 * Auto generated by Extension Builder 2022-03-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Single Sign-on with SAML',
    'description' => 'SSO frontend or backend login with SAML authentication.',
    'category' => 'be',
    'author' => 'Christoph Daecke',
    'author_email' => 'typo3@mediadreams.org',
    'state' => 'stable',
    'version' => '3.0.2',
    'constraints' => [
        'depends' => [
            'typo3' => '12.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
